version: '3'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public/config.json:/usr/share/nginx/html/config.json
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
