version: '3'
services:
  frontend:
    build: .
    ports:
      - "8080:80"  # A porta interna do container é 80, e a externa será 8080
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
