import { useState, useEffect } from "react"
import { SlideData } from "../types/typesAdm"
import { getUserLocalStorage } from "../contexts/AuthProvider/util"

const useSlideData = () => {
  const [slideData, setSlideData] = useState<SlideData>({
    1: {
      title: "",
      sub_title: "",
      text: "",
      any_text: "",
      color_title: "",
      color_sub_title: "",
      color_text: "",
      color_any_text: "",
      font_size_title: "",
      font_weight_title: "",
      font_family_title: "",
      font_size_sub_title: "",
      font_weight_sub_title: "",
      font_family_sub_title: "",
      font_size_text: "",
      font_weight_text: "",
      font_family_text: "",
      font_size_any_text: "",
      font_weight_any_text: "",
      font_family_any_text: "",
    },
    2: {
      title: "",
      sub_title: "",
      text: "",
      any_text: "",
      color_title: "",
      color_sub_title: "",
      color_text: "",
      color_any_text: "",
      font_size_title: "",
      font_weight_title: "",
      font_family_title: "",
      font_size_sub_title: "",
      font_weight_sub_title: "",
      font_family_sub_title: "",
      font_size_text: "",
      font_weight_text: "",
      font_family_text: "",
      font_size_any_text: "",
      font_weight_any_text: "",
      font_family_any_text: "",
    },
    3: {
      title: "",
      sub_title: "",
      text: "",
      any_text: "",
      color_title: "",
      color_sub_title: "",
      color_text: "",
      color_any_text: "",
      font_size_title: "",
      font_weight_title: "",
      font_family_title: "",
      font_size_sub_title: "",
      font_weight_sub_title: "",
      font_family_sub_title: "",
      font_size_text: "",
      font_weight_text: "",
      font_family_text: "",
      font_size_any_text: "",
      font_weight_any_text: "",
      font_family_any_text: "",
    },
    4: {
      title: "",
      sub_title: "",
      text: "",
      any_text: "",
      color_title: "",
      color_sub_title: "",
      color_text: "",
      color_any_text: "",
      font_size_title: "",
      font_weight_title: "",
      font_family_title: "",
      font_size_sub_title: "",
      font_weight_sub_title: "",
      font_family_sub_title: "",
      font_size_text: "",
      font_weight_text: "",
      font_family_text: "",
      font_size_any_text: "",
      font_weight_any_text: "",
      font_family_any_text: "",
    },
    5: {
      title: "",
      sub_title: "",
      text: "",
      any_text: "",
      color_title: "",
      color_sub_title: "",
      color_text: "",
      color_any_text: "",
      font_size_title: "",
      font_weight_title: "",
      font_family_title: "",
      font_size_sub_title: "",
      font_weight_sub_title: "",
      font_family_sub_title: "",
      font_size_text: "",
      font_weight_text: "",
      font_family_text: "",
      font_size_any_text: "",
      font_weight_any_text: "",
      font_family_any_text: "",
    },
  })

  useEffect(() => {
    const fetchSlideData = async () => {
      try {
        const user = getUserLocalStorage()
        const response = await fetch("http://localhost:4000/title", {
          headers: {
            "Authorization": `Bearer ${user?.token}`
          }
        })
        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`)
        }
        const data = await response.json()

        const initialSlideData: SlideData = {
          1: {
            title: "",
            sub_title: "",
            text: "",
            any_text: "",
            color_title: "",
            color_sub_title: "",
            color_text: "",
            color_any_text: "",
            font_size_title: "",
            font_weight_title: "",
            font_family_title: "",
            font_size_sub_title: "",
            font_weight_sub_title: "",
            font_family_sub_title: "",
            font_size_text: "",
            font_weight_text: "",
            font_family_text: "",
            font_size_any_text: "",
            font_weight_any_text: "",
            font_family_any_text: "",
          },
          2: {
            title: "",
            sub_title: "",
            text: "",
            any_text: "",
            color_title: "",
            color_sub_title: "",
            color_text: "",
            color_any_text: "",
            font_size_title: "",
            font_weight_title: "",
            font_family_title: "",
            font_size_sub_title: "",
            font_weight_sub_title: "",
            font_family_sub_title: "",
            font_size_text: "",
            font_weight_text: "",
            font_family_text: "",
            font_size_any_text: "",
            font_weight_any_text: "",
            font_family_any_text: "",
          },
          3: {
            title: "",
            sub_title: "",
            text: "",
            any_text: "",
            color_title: "",
            color_sub_title: "",
            color_text: "",
            color_any_text: "",
            font_size_title: "",
            font_weight_title: "",
            font_family_title: "",
            font_size_sub_title: "",
            font_weight_sub_title: "",
            font_family_sub_title: "",
            font_size_text: "",
            font_weight_text: "",
            font_family_text: "",
            font_size_any_text: "",
            font_weight_any_text: "",
            font_family_any_text: "",
          },
          4: {
            title: "",
            sub_title: "",
            text: "",
            any_text: "",
            color_title: "",
            color_sub_title: "",
            color_text: "",
            color_any_text: "",
            font_size_title: "",
            font_weight_title: "",
            font_family_title: "",
            font_size_sub_title: "",
            font_weight_sub_title: "",
            font_family_sub_title: "",
            font_size_text: "",
            font_weight_text: "",
            font_family_text: "",
            font_size_any_text: "",
            font_weight_any_text: "",
            font_family_any_text: "",
          },
          5: {
            title: "",
            sub_title: "",
            text: "",
            any_text: "",
            color_title: "",
            color_sub_title: "",
            color_text: "",
            color_any_text: "",
            font_size_title: "",
            font_weight_title: "",
            font_family_title: "",
            font_size_sub_title: "",
            font_weight_sub_title: "",
            font_family_sub_title: "",
            font_size_text: "",
            font_weight_text: "",
            font_family_text: "",
            font_size_any_text: "",
            font_weight_any_text: "",
            font_family_any_text: "",
          },
        }

        data.forEach((item: any) => {
          initialSlideData[item.id_text] = {
            title: item.title || "",
            sub_title: item.sub_title || "",
            text: item.text || "",
            any_text: item.any_text || "",
            color_title: item.color_title || "#000000",
            color_sub_title: item.color_sub_title || "#000000",
            color_text: item.color_text || "#000000",
            color_any_text: item.color_any_text || "#000000",
            font_size_title: String(item.font_size_title || 16),
            font_weight_title: item.font_weight_title || "normal",
            font_family_title: item.font_family_title || "Arial",
            font_size_sub_title: String(item.font_size_sub_title || 16),
            font_weight_sub_title: item.font_weight_sub_title || "normal",
            font_family_sub_title: item.font_family_sub_title || "Arial",
            font_size_text: String(item.font_size_text || 16),
            font_weight_text: item.font_weight_text || "normal",
            font_family_text: item.font_family_text || "Arial",
            font_size_any_text: String(item.font_size_any_text || 16),
            font_weight_any_text: item.font_weight_any_text || "normal",
            font_family_any_text: item.font_family_any_text || "Arial",
          }
        })

        setSlideData(initialSlideData)
      } catch (error: any) {
        console.error("Failed to fetch slide data", error)
      }
    }

    fetchSlideData()
  }, [])

  return slideData
}

export default useSlideData
